- name: Create package DevOps
  ansible.builtin.file:
   path: /tmp/devops
   state: directory
  tags: install
   
- name: Clone frontend repository
  git:
   repo: 'https://github.com/Vaival12/frontend.git'
   dest: /tmp/devops/frontend/
  tags: install
   
- name: Clone backend repository
  git:
   repo: 'https://github.com/Vaival12/backend.git'
   dest: /tmp/devops/backend/
  tags: install
  
- name: Copy Docker Backend file
  template:
   src: /var/jenkins_home/workspace/lab4/roles/deploy/templates/DockerfileBackend.yml.j2
   dest: /tmp/devops/backend/Dockerfile
  tags: install
   
- name: Copy Docker Frontend file
  template:
   src: /var/jenkins_home/workspace/lab4/roles/deploy/templates/DockerfileFrontend.yml.j2
   dest: /tmp/devops/frontend/Dockerfile
  tags: install
  
- name: Copy Docker-Compose file
  template:
   src: /var/jenkins_home/workspace/lab4/roles/deploy/templates/docker-compose.yml.j2
   dest: /tmp/devops/docker-compose.yml
  tags: install
