- name: Install git
  apt:
   name: git
   state: present
   update_cache: yes
  tags: install
  become: yes
  
- name: Install curl
  apt:
   name: curl
   state: present
   update_cache: yes
  tags: install
  become: yes
  
- name: Install ssh
  apt:
   name: openssh-server
   state: present
   update_cache: yes
  tags: install
  become: yes
  
- name: Update
  apt:
   update_cache: yes
  become: yes
  tags: install
  
- name: Upgrade
  apt:
   upgrade: dist
  become: yes
  tags: install
  
- name: Install Docker installation script
  get_url:
   url: "https://get.docker.com"
   dest: /tmp/get-docker.sh
  tags: install
  become: yes
  
- name: Run Docker script
  tags: install
  become: yes
  shell: |
   sh /tmp/get-docker.sh

  


