- name: Start microcervices
  tags: start
  command: docker compose up
  args:
   chdir: /tmp/devops
   
- name: Stop microcervices
  tags: stop
  command: docker compose down
  args:
   chdir: /tmp/devops
